[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps =
  bblanchon/ArduinoJson
  https://github.com/mobizt/Firebase-ESP-Client.git
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  marcoschwartz/LiquidCrystal_I2C

build_flags =
  -DCORE_DEBUG_LEVEL=3